#!/usr/bin/env bash
# PreToolUse hook (matcher: Bash) — chặn git commit có AI attribution trong message.
# Đọc JSON tool call từ stdin. Exit 2 + stderr message = block. Exit 0 = allow.
set -euo pipefail

INPUT="$(cat)"

get_command() {
  if command -v jq >/dev/null 2>&1; then
    printf '%s' "$INPUT" | jq -r '.tool_input.command // empty' 2>/dev/null || true
  else
    printf '%s' "$INPUT"
  fi
}

COMMAND="$(get_command)"

if [ -z "$COMMAND" ]; then
  exit 0
fi

if ! printf '%s' "$COMMAND" | grep -qiE 'git[[:space:]]+commit'; then
  exit 0
fi

FORBIDDEN_PATTERNS=(
  'code[[:space:]]+by[[:space:]]+claude'
  'generated[[:space:]]+by[[:space:]]+claude'
  'ai[[:space:]]+generated'
  'co-authored-by:[[:space:]]*claude'
  'written[[:space:]]+by[[:space:]]+claude'
  'claude[[:space:]]+code'
)

for pattern in "${FORBIDDEN_PATTERNS[@]}"; do
  if printf '%s' "$COMMAND" | grep -qiE "$pattern"; then
    echo "[block-ai-attribution-commit-msg] Commit message chứa cụm bị cấm liên quan AI attribution (khớp: $pattern)." >&2
    echo "Bỏ các cụm như 'code by claude', 'generated by claude', 'AI generated', 'Co-authored-by: Claude' khỏi commit message." >&2
    exit 2
  fi
done

exit 0
